LorestanKala/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('accounts/',include('allauth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name="cart"

urlpatterns=[
    url(r'^$', views.detail_cart, name='cart_detail'),
    url(r"^add/(?P<product_id>\d+)/$", views.add_cart, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.remove_cart, name='cart_remove'),
]

shop/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from . import views

app_name="shop"

urlpatterns=[
    path('',views.index,name='index'),
    url(r'^(?P<category_slug>\W+)/$',views.index,name='list_by_category'),
    url(r'^product/(?P<pk>\d+)/$',views.ProductDetail,name='product_detail'),
    path('Category/<int:id>/',views.product_by_category,name='product_by_category'),
    path('login/',views.login,name='login'),
    path('register/',views.Register,name='register'),
    path('change-password/',views.change_password,name='change_password'),
    path('base/',views.base,name='base'),
    path('search/',views.search,name='search')



]

Gallery/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post">
     {% csrf_token %}

    {{ form.as_p }}
    <input type="submit" value="submit">

</form>

</body>
</html>

Gallery/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="get" action="{% url 'shop:search' %}">
    {% csrf_token %}
    <input name="q" value="{{ request.GET.q }}" placeholder="search...">
    <button class="btn btn-success" type="submit">
        search
    </button>
</form>
</body>
</html>